ESTILO_FONT_MUITO_PEQUENA = ['Arial', 10]
ESTILO_FONT_PEQUENA = ['Arial', 15]
ESTILO_FONT_MEDIA = ['Arial', 20]
ESTILO_FONT_GRANDE = ['Arial', 30]
ESTABELECIMENTO = "Mercado Tio Salim"

COR_FUNDO_TITULO = '#f39c12'
COR_FUNDO_PRIMARIA = '#f39c12'
COR_SECUNDARIA = '#2980b9'
COR_TEXTO_PRIMARIA = '#fff'
