ESTILO_FONT_MUITO_PEQUENA = ['Arial', 10]
ESTILO_FONT_PEQUENA = ['Arial', 15]
ESTILO_FONT_MEDIA = ['Arial', 20]
ESTILO_FONT_GRANDE = ['Arial', 30]
ESTILO_FONT_MUITO_GRANDE = ['Arial', 80]
ESTILO_FONT_TELA_PRINCIPAL_MUITO_GRANDE = ['Dancing Script Bold', 120]
ESTILO_FONT_TELA_PRINCIPAL_GRANDE = ['Dancing Script Bold', 80]
ESTILO_FONT_TELA_PRINCIPAL_MEDIA = ['Dancing Script Bold', 40]
ESTABELECIMENTO = "Mercado Tio Salim"

COR_FUNDO_TITULO = '#f39c12'
COR_FUNDO_PRIMARIA = '#f39c12'
COR_FUNDO_SECUNDARIA = '#333' #'#2980b9'
COR_TEXTO_PRIMARIA = '#fff'

CINZA_CHUMBO = '#2c3e50'

IMAGEM_PEQUENA = [250, 250]
IMAGEM_GRANDE = [400, 400]
